require 'Items/Distributions'
require 'Items/SuburbsDistributions'
require 'Items/ProceduralDistributions'
require 'Vehicles/VehicleDistributions'


local i, j, d

-- REGULAR BOOKS distribution for ProceduralDistributions.lua
local myDistTable = {
  "Antiques", 0.1,
  "BathroomShelf", 0.01,
  "BookstoreBooks", 2,
  "CampingStoreBooks", 1,
  "ClassroomDesk", 0.001,
  "ClassroomMisc", 0.001,
  "ClassroomShelves", 0.01,
  "CrateBooks", 2,
  "CrateRandomJunk", 0.01,
  "DaycareDesk", 0.01,
  "KitchenBook", 0.01,
  "LibraryBooks", 3,
  "LibraryCounter", 0.01,
  "LivingRoomShelf", 0.1,
  "LivingRoomShelfNoTapes", 0.1,
  "Locker", 0.01,
  "MedicalOfficeBooks", 0.01,
  "OfficeCounter", 0.01,
  "OtherGeneric", 0.01,
  "PostOfficeBooks", 0.1,
  "RandomFiller", 0.001,
  "SchoolLockers", 0.001,
  "ShelfGeneric", 0.001,
  "ToolStoreBooks", 0.01,
  "ClosetShelfGeneric", 0.1,
  "VacationStuff", 0.1,
}

for i = 1, #myDistTable, 2 do
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_1")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_2")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_3")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_4")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_5")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_6")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_7")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_8")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_9")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_10")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_11")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_12")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_13")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_14")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_15")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_16")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_17")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_18")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_19")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_20")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_21")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_22")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_23")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_24")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_25")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_26")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_27")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_28")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_29")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_30")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_31")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_32")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_33")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_34")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_35")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_36")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_37")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_38")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_39")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_40")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_41")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_42")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_43")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_44")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_45")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_46")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_47")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_48")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_49")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_50")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_51")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_52")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_53")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_54")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_55")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_56")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_57")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_58")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_59")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_60")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_61")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_62")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_63")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_64")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_65")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_66")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_67")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_68")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_69")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_70")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_71")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_72")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_73")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_74")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_75")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_76")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_77")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_78")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_79")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_80")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_81")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_82")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_83")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_84")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_85")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_86")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_87")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_88")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_89")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_90")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_91")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_92")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_93")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_94")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_95")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_96")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_97")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_98")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_99")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_100")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_101")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_102")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_103")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_104")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_105")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_106")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_107")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_108")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_109")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_110")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_111")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_112")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_113")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_114")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_115")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_116")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_117")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_118")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_119")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_120")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_121")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_122")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_123")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_124")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.book_ukrlit_125")
  table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
end
myDistTable = nil


-- REGULAR Magazines distribution for ProceduralDistributions.lua
local myDistTable = {
  "Antiques", 0.1,
  "BathroomShelf", 0.01,
  "BedroomSideTable", 0.1,
  "BookstoreMisc", 0.1,
  "BreakRoomShelves", 0.1,
  "CafeShelfBooks", 0.1,
  "CampingStoreBooks", 1,
  "ClassroomDesk", 0.01,
  "ClassroomMisc", 0.01,
  "ClassroomShelves", 0.01,
  "CrateBooks", 0.01,
  "CrateMagazines", 10,
  "CrateRandomJunk", 0.01,
  "DaycareDesk", 0.1,
  "DeskGeneric", 0.1,
  "ElectronicStoreMagazines", 1,
  "ElectronicStoreMusic", 0.1,
  "GarageFirearms", 0.1,
  "GunStoreMagazineRack", 2,
  "Hobbies", 0.1,
  "JanitorMisc", 0.01,
  "JunkHoard", 0.01,
  "LibraryCounter", 0.01,
  "LivingRoomShelf", 0.1,
  "LivingRoomShelfNoTapes", 0.1,
  "LivingRoomSideTable", 0.1,
  "LivingRoomShelfNoTapes", 0.1,
  "LivingRoomSideTableNoRemote", 0.1,
  "LibraryBooks", 0.1,
  "Locker", 0.001,
  "MagazineRackMixed", 2,
  "MechanicShelfBooks", 0.1,
  "MechanicShelfMisc", 0.1,
  "MusicStoreSpeaker", 0.01,
  "MechanicShelfBooks", 0.01,
  "OfficeCounter", 0.1,
  "OfficeDesk", 0.1,
  "OfficeDeskHome", 0.1,
  "OfficeDrawers", 0.1,
  "PoliceDesk", 0.1,
  "PostOfficeMagazines", 1,
  "PrisonCellRandom", 0.1,
  "RandomFiller", 0.001,
  "SchoolLockers", 0.001,
  "ShelfGeneric", 0.001,
  "OtherGeneric", 0.001,
  "VacationStuff", 0.001,
   }

  for i = 1, #myDistTable, 2 do
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_1")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_2")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_3")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_4")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_5")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_6")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_7")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_8")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_9")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_10")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_11")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_12")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_13")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_14")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_15")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_16")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_17")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_18")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_19")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_20")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_21")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_22")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_23")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_24")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_25")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_26")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_27")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_28")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_29")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_30")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_31")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_32")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_33")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_34")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_35")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_36")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_37")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_38")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_39")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_40")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_41")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_42")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_43")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_44")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_45")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_46")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_47")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_48")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_49")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_magazine_50")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])

  end
  myDistTable = nil


---- 1-3 lvl books Distributions for VEHICLES VehicleDistributions.lua. May be broken in next updates due devs going to ProceduralDistributions
myDistTable = nil
myDistTable = {
  "GloveBox", 0.01,
  "TrunkStandard", 0.01,
  "TrunkHeavy", 0.01,
  "TrunkSports", 0.01,
  "FarmerTruckBed", 0.01,
  "PostalTruckBed", 0.01,
  "SurvivalistTruckBed", 0.01,
}

for i = 1, #myDistTable, 2 do
  table.insert(VehicleDistributions[myDistTable[i]].items, "prosvita_books.ukr_magazine_1")
  table.insert(VehicleDistributions[myDistTable[i]].items, myDistTable[i+1])
  table.insert(VehicleDistributions[myDistTable[i]].items, "prosvita_books.ukr_magazine_2")
  table.insert(VehicleDistributions[myDistTable[i]].items, myDistTable[i+1])
  table.insert(VehicleDistributions[myDistTable[i]].items, "prosvita_books.ukr_magazine_3")
  table.insert(VehicleDistributions[myDistTable[i]].items, myDistTable[i+1])
  table.insert(VehicleDistributions[myDistTable[i]].items, "prosvita_books.ukr_magazine_4")
  table.insert(VehicleDistributions[myDistTable[i]].items, myDistTable[i+1])
  table.insert(VehicleDistributions[myDistTable[i]].items, "prosvita_books.ukr_magazine_5")
  table.insert(VehicleDistributions[myDistTable[i]].items, myDistTable[i+1])
  table.insert(VehicleDistributions[myDistTable[i]].items, "prosvita_books.ukr_magazine_6")
  table.insert(VehicleDistributions[myDistTable[i]].items, myDistTable[i+1])
  table.insert(VehicleDistributions[myDistTable[i]].items, "prosvita_books.ukr_magazine_7")
  table.insert(VehicleDistributions[myDistTable[i]].items, myDistTable[i+1])
  table.insert(VehicleDistributions[myDistTable[i]].items, "prosvita_books.ukr_magazine_8")
  table.insert(VehicleDistributions[myDistTable[i]].items, myDistTable[i+1])
  table.insert(VehicleDistributions[myDistTable[i]].items, "prosvita_books.ukr_magazine_9")
  table.insert(VehicleDistributions[myDistTable[i]].items, myDistTable[i+1])
  table.insert(VehicleDistributions[myDistTable[i]].items, "prosvita_books.ukr_magazine_10")
  table.insert(VehicleDistributions[myDistTable[i]].items, myDistTable[i+1])
  table.insert(VehicleDistributions[myDistTable[i]].items, "prosvita_books.ukr_magazine_11")
  table.insert(VehicleDistributions[myDistTable[i]].items, myDistTable[i+1])
  table.insert(VehicleDistributions[myDistTable[i]].items, "prosvita_books.ukr_magazine_12")
  table.insert(VehicleDistributions[myDistTable[i]].items, myDistTable[i+1])
  table.insert(VehicleDistributions[myDistTable[i]].items, "prosvita_books.ukr_magazine_13")
  table.insert(VehicleDistributions[myDistTable[i]].items, myDistTable[i+1])
  table.insert(VehicleDistributions[myDistTable[i]].items, "prosvita_books.ukr_magazine_14")
  table.insert(VehicleDistributions[myDistTable[i]].items, myDistTable[i+1])
  table.insert(VehicleDistributions[myDistTable[i]].items, "prosvita_books.ukr_magazine_15")
  table.insert(VehicleDistributions[myDistTable[i]].items, myDistTable[i+1])
end
myDistTable = nil


-- ADULT literature destributiuon for ProceduralDistributions.lua
  local myDistTable = {
  "Antiques", 0.001,
  "BookstoreBooks", 0.01,
  "ClassroomDesk", 0.0001,
  "LibraryCounter", 0.001,
  "LivingRoomShelf", 0.001,
  "LivingRoomShelfNoTapes", 0.001,
  "Locker", 0.001,
  "SchoolLockers", 0.001,
  "WardrobeManClassy", 0.01,
  "PlankStashMagazine", 1,
  "PostOfficeMagazines", 0.01,
  "PrisonCellRandom", 0.1,
  "MagazineRackMixed", 0.01,
  "MechanicShelfMisc", 0.001,
  "JanitorMisc", 0.1,
  "CrateMagazines", 0.01,
  "BathroomShelf", 0.1,
  }

    for i = 1, #myDistTable, 2 do
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_adultmag_1")
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_adultmag_2")
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_adultmag_3")
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_adultmag_4")
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_adultmag_5")
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_adultmag_6")
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_adultmag_7")
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_adultmag_8")
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_adultmag_9")
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_adultmag_10")
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_adultmag_11")
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_adultmag_12")
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_adultmag_13")
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_adultmag_14")
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_adultmag_15")
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_adultmag_16")
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_adultmag_17")
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_adultmag_18")
      table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    end
    myDistTable = nil


-- COMICS distribution for ProceduralDistributions.lua
local myDistTable = {
  "BookstoreMisc", 0.01,
  "CafeShelfBooks", 0.1,
  "CrateComics", 2,
  "CrateMagazines", 0.1,
  "CrateRandomJunk", 0.001,
  "DaycareDesk", 0.001,
  "Hobbies", 0.01,
  "JanitorMisc", 0.01,
  "JunkHoard", 0.001,
  "LivingRoomShelf", 0.01,
  "LivingRoomShelfNoTapes", 0.001,
  "LivingRoomSideTable", 0.001,
  "LivingRoomSideTableNoRemote", 0.01,
  "LibraryBooks", 0.001,
  "Locker", 0.001,
  "MagazineRackMixed", 0.01,
  "SchoolLockers", 0.001,
   }

  for i = 1, #myDistTable, 2 do
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_1")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_2")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_3")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_4")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_5")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_6")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_7")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_8")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_9")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_10")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_11")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_12")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_13")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_14")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_15")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_16")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_17")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_18")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_19")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_20")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_21")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_22")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_23")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_24")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_25")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_26")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_27")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_28")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_29")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_30")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_31")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_32")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_33")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_34")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_35")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_36")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_37")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_38")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_39")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_40")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_41")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_42")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_43")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_44")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_45")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_46")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_47")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_48")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_49")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, "prosvita_books.ukr_comics_50")
    table.insert(ProceduralDistributions.list[myDistTable[i]].items, myDistTable[i+1])

  end
  myDistTable = nil
