local ItemDist = {
  -- Ukrainian Literature Distribution
  {
    Distributions = {
      {"BathroomShelf", 0.01},
      {"BookstoreBooks", 0.05},
      {"CampingStoreBooks", 0.01},
      {"ClassroomDesk", 0.0001},
      {"ClassroomMisc", 0.00001},
      {"ClassroomShelves", 0.0001},
      {"SchoolLockers", 0.00001},
      {"CrateBooks", 0.01},
      {"CrateRandomJunk", 0.0001},
      {"DaycareDesk", 0.001},
      {"KitchenBook", 0.001},
      {"LibraryBooks", 0.05},
      {"LibraryCounter", 0.01},
      {"BathroomShelf", 0.001},
      {"LivingRoomShelf", 0.0001},
      {"LivingRoomShelfNoTapes", 0.0001},
      {"Locker", 0.0005},
      {"MedicalOfficeBooks", 0.0001},
      {"OfficeCounter", 0.0001},
      {"OtherGeneric", 0.00001},
      {"PostOfficeBooks", 0.0001},
      {"RandomFiller", 0.00001},
      {"ShelfGeneric", 0.0001},
      {"ClosetShelfGeneric", 0.001},
      {"VacationStuff", 0.001},
    },
    Items = {
"prosvita_books.book_ukrlit_1",
"prosvita_books.book_ukrlit_2",
"prosvita_books.book_ukrlit_3",
"prosvita_books.book_ukrlit_4",
"prosvita_books.book_ukrlit_5",
"prosvita_books.book_ukrlit_6",
"prosvita_books.book_ukrlit_7",
"prosvita_books.book_ukrlit_8",
"prosvita_books.book_ukrlit_9",
"prosvita_books.book_ukrlit_10",
"prosvita_books.book_ukrlit_11",
"prosvita_books.book_ukrlit_12",
"prosvita_books.book_ukrlit_13",
"prosvita_books.book_ukrlit_14",
"prosvita_books.book_ukrlit_15",
"prosvita_books.book_ukrlit_16",
"prosvita_books.book_ukrlit_17",
"prosvita_books.book_ukrlit_18",
"prosvita_books.book_ukrlit_19",
"prosvita_books.book_ukrlit_20",
"prosvita_books.book_ukrlit_21",
"prosvita_books.book_ukrlit_22",
"prosvita_books.book_ukrlit_23",
"prosvita_books.book_ukrlit_24",
"prosvita_books.book_ukrlit_25",
"prosvita_books.book_ukrlit_26",
"prosvita_books.book_ukrlit_27",
"prosvita_books.book_ukrlit_28",
"prosvita_books.book_ukrlit_29",
"prosvita_books.book_ukrlit_30",
"prosvita_books.book_ukrlit_31",
"prosvita_books.book_ukrlit_32",
"prosvita_books.book_ukrlit_33",
"prosvita_books.book_ukrlit_34",
"prosvita_books.book_ukrlit_35",
"prosvita_books.book_ukrlit_36",
"prosvita_books.book_ukrlit_37",
"prosvita_books.book_ukrlit_38",
"prosvita_books.book_ukrlit_39",
"prosvita_books.book_ukrlit_40",
"prosvita_books.book_ukrlit_41",
"prosvita_books.book_ukrlit_42",
"prosvita_books.book_ukrlit_43",
"prosvita_books.book_ukrlit_44",
"prosvita_books.book_ukrlit_45",
"prosvita_books.book_ukrlit_46",
"prosvita_books.book_ukrlit_47",
"prosvita_books.book_ukrlit_48",
"prosvita_books.book_ukrlit_49",
"prosvita_books.book_ukrlit_50",
"prosvita_books.book_ukrlit_51",
"prosvita_books.book_ukrlit_52",
"prosvita_books.book_ukrlit_53",
"prosvita_books.book_ukrlit_54",
"prosvita_books.book_ukrlit_55",
"prosvita_books.book_ukrlit_56",
"prosvita_books.book_ukrlit_57",
"prosvita_books.book_ukrlit_58",
"prosvita_books.book_ukrlit_59",
"prosvita_books.book_ukrlit_60",
"prosvita_books.book_ukrlit_61",
"prosvita_books.book_ukrlit_62",
"prosvita_books.book_ukrlit_63",
"prosvita_books.book_ukrlit_64",
"prosvita_books.book_ukrlit_65",
"prosvita_books.book_ukrlit_66",
"prosvita_books.book_ukrlit_67",
"prosvita_books.book_ukrlit_68",
"prosvita_books.book_ukrlit_69",
"prosvita_books.book_ukrlit_70",
"prosvita_books.book_ukrlit_71",
"prosvita_books.book_ukrlit_72",
"prosvita_books.book_ukrlit_73",
"prosvita_books.book_ukrlit_74",
"prosvita_books.book_ukrlit_75",
"prosvita_books.book_ukrlit_76",
"prosvita_books.book_ukrlit_77",
"prosvita_books.book_ukrlit_78",
"prosvita_books.book_ukrlit_79",
"prosvita_books.book_ukrlit_80",
"prosvita_books.book_ukrlit_81",
"prosvita_books.book_ukrlit_82",
"prosvita_books.book_ukrlit_83",
"prosvita_books.book_ukrlit_84",
"prosvita_books.book_ukrlit_85",
"prosvita_books.book_ukrlit_86",
"prosvita_books.book_ukrlit_87",
"prosvita_books.book_ukrlit_88",
"prosvita_books.book_ukrlit_89",
"prosvita_books.book_ukrlit_90",
"prosvita_books.book_ukrlit_91",
"prosvita_books.book_ukrlit_92",
"prosvita_books.book_ukrlit_93",
"prosvita_books.book_ukrlit_94",
"prosvita_books.book_ukrlit_95",
"prosvita_books.book_ukrlit_96",
"prosvita_books.book_ukrlit_97",
"prosvita_books.book_ukrlit_98",
"prosvita_books.book_ukrlit_99",
"prosvita_books.book_ukrlit_100",
"prosvita_books.book_ukrlit_101",
"prosvita_books.book_ukrlit_102",
"prosvita_books.book_ukrlit_103",
"prosvita_books.book_ukrlit_104",
"prosvita_books.book_ukrlit_105",
"prosvita_books.book_ukrlit_106",
"prosvita_books.book_ukrlit_107",
"prosvita_books.book_ukrlit_108",
"prosvita_books.book_ukrlit_109",
"prosvita_books.book_ukrlit_110",
"prosvita_books.book_ukrlit_111",
"prosvita_books.book_ukrlit_112",
"prosvita_books.book_ukrlit_113",
"prosvita_books.book_ukrlit_114",
"prosvita_books.book_ukrlit_115",
"prosvita_books.book_ukrlit_116",
"prosvita_books.book_ukrlit_117",
"prosvita_books.book_ukrlit_118",
"prosvita_books.book_ukrlit_119",
"prosvita_books.book_ukrlit_120",
"prosvita_books.book_ukrlit_121",
"prosvita_books.book_ukrlit_122",
"prosvita_books.book_ukrlit_123",
"prosvita_books.book_ukrlit_124",
"prosvita_books.book_ukrlit_125",
  }
  },


  -- next item distribution group
  -- ...
}



local function getLootTable(strLootTableName)
  return ProceduralDistributions.list[strLootTableName]
end

local function insertItem(tLootTable, strItem, iWeight)
  table.insert(tLootTable.items, strItem)
  table.insert(tLootTable.items, iWeight)
end

local function preDistributionMerge()
  for i=1, #ItemDist do
    for j=1, #(ItemDist[i].Distributions) do
      for k=1, #(ItemDist[i].Items) do
        local tLootTable = getLootTable(ItemDist[i].Distributions[j][1])
        local strItem = ItemDist[i].Items[k]
        local iWeight = ItemDist[i].Distributions[j][2]
        insertItem(tLootTable, strItem, iWeight)
      end
    end
  end
end
Events.OnPreDistributionMerge.Add(preDistributionMerge)
