require 'Items/ProceduralDistributions'
require 'Items/Distributions'

table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_prosvita_sprint_1");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.1);
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_prosvita_sprint_2");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.07);
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_prosvita_sprint_3");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.05);
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_prosvita_sprint_4");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.02);
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_prosvita_sprint_5");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.01);

table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_prosvita_agility_1");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.1);
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_prosvita_agility_2");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.07);
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_prosvita_agility_3");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.05);
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_prosvita_agility_4");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.02);
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_prosvita_agility_5");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.01);

table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_prosvita_lightfoot_1");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.1);
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_prosvita_lightfoot_2");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.07);
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_prosvita_lightfoot_3");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.05);
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_prosvita_lightfoot_4");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.02);
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_prosvita_lightfoot_5");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.01);

table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_prosvita_stealth_1");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.1);
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_prosvita_stealth_2");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.07);
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_prosvita_stealth_3");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.05);
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_prosvita_stealth_4");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.02);
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_prosvita_stealth_5");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.01);

table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_prosvita_strength_1");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.1);
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_prosvita_strength_2");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.07);
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_prosvita_strength_3");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.05);
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_prosvita_strength_4");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.02);
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_prosvita_strength_5");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.01);

table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_prosvita_fitness_1");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.1);
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_prosvita_fitness_2");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.07);
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_prosvita_fitness_3");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.05);
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_prosvita_fitness_4");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.02);
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_prosvita_fitness_5");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.01);

table.insert(ProceduralDistributions.list["SurvivalGear"].items, "prosvita_books.book_maintenance_1");
table.insert(ProceduralDistributions.list["SurvivalGear"].items, 0.1);
table.insert(ProceduralDistributions.list["SurvivalGear"].items, "prosvita_books.book_maintenance_2");
table.insert(ProceduralDistributions.list["SurvivalGear"].items, 0.07);
table.insert(ProceduralDistributions.list["SurvivalGear"].items, "prosvita_books.book_maintenance_3");
table.insert(ProceduralDistributions.list["SurvivalGear"].items, 0.05);
table.insert(ProceduralDistributions.list["SurvivalGear"].items, "prosvita_books.book_maintenance_4");
table.insert(ProceduralDistributions.list["SurvivalGear"].items, 0.02);
table.insert(ProceduralDistributions.list["SurvivalGear"].items, "prosvita_books.book_maintenance_5");
table.insert(ProceduralDistributions.list["SurvivalGear"].items, 0.01);

table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_maintenance_1");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.1);
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_maintenance_2");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.07);
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_maintenance_3");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.05);
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_maintenance_4");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.02);
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "prosvita_books.book_maintenance_5");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.01);
